### ISSUE TITLE
cannot create a vm outside of the region a storage account is in

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#57]
Given an azurectl account with a storage account in region X, VMs cannot be created in any region except X.

Trying to instantiate a VM in a different region throws the following error (the storage account used here was in West US, the argument was `--region="East US 2"`):

```
ERROR: AzureVmCreateError: 'AzureHttpError: Bad Request\n<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The location or affinity group West US of the storage account where the source image b4590d9e3ed742e4a1d46e5424aa335e__suse-sles-11-sp4-v20150714 resides is not in the same location or affinity group as the specified cloud service. The source image must reside in a storage account that has the same affinity group or location as the cloud service East US 2.</Message></Error>'
```

*Note:* This error is currently masked by another error:

```
ERROR: AzureVmCreateError: 'AzureHttpError: Bad Request\n<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>MediaLocation is only applicable when using a published VM Image. It cannot be used with user VM Images, OS or data virtual hard disks.</Message></Error>'
```

You must patch out `virtual_machine.py` line 120 to work around this error.

I'm including both here, because there's obviously some issues around location handling that need to be solved in both VM creation and the config file; it would be better to resolve the overall issue than to just patch around the the 2nd error.

**Comment by rjschwei** [comment]
We need to split the region dependent information from the account information. My suggestion is to follow the pattern of the config file we use for the ec2utils.

[account-]
[region-]

In the region section we can store the storage account information as follows

[region-us-east]
default_storage=mybucket
storage_accounts=a_bucket,b_bucket,c_bucket

The [account-] section holds information about Azure access.

If a user instantiates and instance with --region we look in the config file for a storage account. If there is none configured for the given region we create one and add the information to the config file. If a storage account exists we use the value for default_storage unless otherwise directed by a --storage-account command line option.

**Comment by schaefi** [comment]
ok I like the idea to have region sections containing storage and container information

I don't like to automatically create a storage account, this sounds like making possibly unwanted user decisions. Overall I don't like tools which tries to be more intelligent than the user :) Instead if no config for the region exists an error should be thrown

azurectl should provide commands to create a storage account which belongs to "azurectl compute storage ..."  and a way to setup a new region in the config file with "azurectl account region ..."

no magic please

As you can see this ends up in the following tasks

1. refactor use of config file with new region sections, storage account handling for all existing tasks
2. add command to add region configuration to config file
3. add command to create storage accounts

I can work on this, however I'd like to postpone the last task because I have the feeling we will never release version one of azurectl otherwise

Thoughts

**Comment by schaefi** [comment]
I started to work on the config file refactoring, I'll come up with a branch on Monday

**Comment by rjschwei** [comment]
On 10/02/2015 05:39 AM, Marcus Schäfer wrote:
> ok I like the idea to have region sections containing storage and container information
> 
> I don't like to automatically create a storage account, this sounds like making possibly unwanted user decisions. Overall I don't like tools which tries to be more intelligent than the user :) Instead if no config for the region exists an error should be thrown

Fair enough. Less magic is better. Lets have a command line argument (as
an improvement in the future) that allows the user to direct the tool to
create missing storage accounts when necessary. For now lets just
generate an error message.

> 
> azurectl should provide commands to create a storage account which belongs to "azurectl compute storage ..."  and a way to setup a new region in the config file with "azurectl account region ..."
> 
> no magic please
> 
> As you can see this ends up in the following tasks
> 
> 1. refactor use of config file with new region sections, storage account handling for all existing tasks
> 2. add command to add region configuration to config file
> 3. add command to create storage accounts
> 
> I can work on this, however I'd like to postpone the last task because I have the feeling we will never release version one of azurectl otherwise

Agreed.



-- 
Robert Schweikert                   MAY THE SOURCE BE WITH YOU
Public Cloud Architect                         LINUX
rjschwei@suse.com
IRC: robjo

**Comment by schaefi** [comment]
Version 1.0.0 is now building and fixes this issue
